# Project Name
TARGET = fjol

# Sources
CPP_SOURCES = fjol.cpp variables.cpp midi.cpp calibrate.cpp led-enc.cpp

# Library Locations
LIBDAISY_DIR = libDaisy
DAISYSP_DIR = DaisySP
APP_TYPE = BOOT_SRAM #this is to be able to write firmware using the bootloader


# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile

