# Project Name
TARGET = fjol

# Sources
CPP_SOURCES = fjol.cpp variables.cpp midi.cpp calibrate.cpp

# Library Locations
LIBDAISY_DIR = libDaisy
DAISYSP_DIR = DaisySP

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile

